---
- name: Initial setup
  hosts: all
  become: yes
  roles:
    - create-sudo-user
    - update
    #- set-hostname # this one is useful in enterprise context, with a hostname based inventory under a common domain name
    #- install-modules # this one is useful to install common packages if your templates are not up to date yet
  tags: always

- name: Reboot
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - reboot
  tags: [ never, reboot ]
